// Generated by Metro-MPI Tool

#include <mpi.h>
#include <cstdint>
#include <cstddef>
#include <iostream>

using std::cout;
using std::endl;

// Global mask table: index represents bit-width (0 to 64)
static const unsigned long long metro_bit_masks[] = {
    0x0ULL,  // Width 0 (Unused)
    0x1ULL,  // Width 1
    0x3ULL,  // Width 2
    0x7ULL,  // Width 3
    0xFULL,  // Width 4
    0x1FULL,  // Width 5
    0x3FULL,  // Width 6
    0x7FULL,  // Width 7
    0xFFULL,  // Width 8
    0x1FFULL,  // Width 9
    0x3FFULL,  // Width 10
    0x7FFULL,  // Width 11
    0xFFFULL,  // Width 12
    0x1FFFULL,  // Width 13
    0x3FFFULL,  // Width 14
    0x7FFFULL,  // Width 15
    0xFFFFULL,  // Width 16
    0x1FFFFULL,  // Width 17
    0x3FFFFULL,  // Width 18
    0x7FFFFULL,  // Width 19
    0xFFFFFULL,  // Width 20
    0x1FFFFFULL,  // Width 21
    0x3FFFFFULL,  // Width 22
    0x7FFFFFULL,  // Width 23
    0xFFFFFFULL,  // Width 24
    0x1FFFFFFULL,  // Width 25
    0x3FFFFFFULL,  // Width 26
    0x7FFFFFFULL,  // Width 27
    0xFFFFFFFULL,  // Width 28
    0x1FFFFFFFULL,  // Width 29
    0x3FFFFFFFULL,  // Width 30
    0x7FFFFFFFULL,  // Width 31
    0xFFFFFFFFULL,  // Width 32
    0x1FFFFFFFFULL,  // Width 33
    0x3FFFFFFFFULL,  // Width 34
    0x7FFFFFFFFULL,  // Width 35
    0xFFFFFFFFFULL,  // Width 36
    0x1FFFFFFFFFULL,  // Width 37
    0x3FFFFFFFFFULL,  // Width 38
    0x7FFFFFFFFFULL,  // Width 39
    0xFFFFFFFFFFULL,  // Width 40
    0x1FFFFFFFFFFULL,  // Width 41
    0x3FFFFFFFFFFULL,  // Width 42
    0x7FFFFFFFFFFULL,  // Width 43
    0xFFFFFFFFFFFULL,  // Width 44
    0x1FFFFFFFFFFFULL,  // Width 45
    0x3FFFFFFFFFFFULL,  // Width 46
    0x7FFFFFFFFFFFULL,  // Width 47
    0xFFFFFFFFFFFFULL,  // Width 48
    0x1FFFFFFFFFFFFULL,  // Width 49
    0x3FFFFFFFFFFFFULL,  // Width 50
    0x7FFFFFFFFFFFFULL,  // Width 51
    0xFFFFFFFFFFFFFULL,  // Width 52
    0x1FFFFFFFFFFFFFULL,  // Width 53
    0x3FFFFFFFFFFFFFULL,  // Width 54
    0x7FFFFFFFFFFFFFULL,  // Width 55
    0xFFFFFFFFFFFFFFULL,  // Width 56
    0x1FFFFFFFFFFFFFFULL,  // Width 57
    0x3FFFFFFFFFFFFFFULL,  // Width 58
    0x7FFFFFFFFFFFFFFULL,  // Width 59
    0xFFFFFFFFFFFFFFFULL,  // Width 60
    0x1FFFFFFFFFFFFFFFULL,  // Width 61
    0x3FFFFFFFFFFFFFFFULL,  // Width 62
    0x7FFFFFFFFFFFFFFFULL,  // Width 63
    0xFFFFFFFFFFFFFFFFULL  // Width 64
};

// Struct for communication from rank 0 to 1
struct mpi_rank_0_to_1_t {
    long long logic_a; // -> maps to receiver port a
    long long logic_b; // -> maps to receiver port b
    long long logic_op; // -> maps to receiver port op
};

MPI_Datatype mpi_type_rank_0_to_1;

// Struct for communication from rank 0 to 2
struct mpi_rank_0_to_2_t {
    long long logic_a; // -> maps to receiver port a
    long long logic_b; // -> maps to receiver port b
    long long logic_op; // -> maps to receiver port op
};

MPI_Datatype mpi_type_rank_0_to_2;

// Struct for communication from rank 0 to 3
struct mpi_rank_0_to_3_t {
    long long logic_a; // -> maps to receiver port a
    long long logic_b; // -> maps to receiver port b
    long long logic_op; // -> maps to receiver port op
};

MPI_Datatype mpi_type_rank_0_to_3;

// Struct for communication from rank 0 to 4
struct mpi_rank_0_to_4_t {
    long long logic_a; // -> maps to receiver port a
    long long logic_b; // -> maps to receiver port b
    long long logic_op; // -> maps to receiver port op
};

MPI_Datatype mpi_type_rank_0_to_4;

// Struct for communication from rank 1 to 0
struct mpi_rank_1_to_0_t {
    long long y; // -> maps to receiver port logic_y
};

MPI_Datatype mpi_type_rank_1_to_0;

// Struct for communication from rank 2 to 0
struct mpi_rank_2_to_0_t {
    long long y; // -> maps to receiver port logic_y
};

MPI_Datatype mpi_type_rank_2_to_0;

// Struct for communication from rank 3 to 0
struct mpi_rank_3_to_0_t {
    long long y; // -> maps to receiver port logic_y
};

MPI_Datatype mpi_type_rank_3_to_0;

// Struct for communication from rank 4 to 0
struct mpi_rank_4_to_0_t {
    long long y; // -> maps to receiver port logic_y
};

MPI_Datatype mpi_type_rank_4_to_0;


void initialize_mpi_types() {
    {
        const int nitems = 3;
        int blocklengths[3] = {1, 1, 1};
        MPI_Datatype types[3] = {MPI_LONG_LONG, MPI_LONG_LONG, MPI_LONG_LONG};
        MPI_Aint offsets[3];
        offsets[0] = offsetof(mpi_rank_0_to_1_t, logic_a);
        offsets[1] = offsetof(mpi_rank_0_to_1_t, logic_b);
        offsets[2] = offsetof(mpi_rank_0_to_1_t, logic_op);
        MPI_Type_create_struct(nitems, blocklengths, offsets, types, &mpi_type_rank_0_to_1);
        MPI_Type_commit(&mpi_type_rank_0_to_1);
    }
    {
        const int nitems = 3;
        int blocklengths[3] = {1, 1, 1};
        MPI_Datatype types[3] = {MPI_LONG_LONG, MPI_LONG_LONG, MPI_LONG_LONG};
        MPI_Aint offsets[3];
        offsets[0] = offsetof(mpi_rank_0_to_2_t, logic_a);
        offsets[1] = offsetof(mpi_rank_0_to_2_t, logic_b);
        offsets[2] = offsetof(mpi_rank_0_to_2_t, logic_op);
        MPI_Type_create_struct(nitems, blocklengths, offsets, types, &mpi_type_rank_0_to_2);
        MPI_Type_commit(&mpi_type_rank_0_to_2);
    }
    {
        const int nitems = 3;
        int blocklengths[3] = {1, 1, 1};
        MPI_Datatype types[3] = {MPI_LONG_LONG, MPI_LONG_LONG, MPI_LONG_LONG};
        MPI_Aint offsets[3];
        offsets[0] = offsetof(mpi_rank_0_to_3_t, logic_a);
        offsets[1] = offsetof(mpi_rank_0_to_3_t, logic_b);
        offsets[2] = offsetof(mpi_rank_0_to_3_t, logic_op);
        MPI_Type_create_struct(nitems, blocklengths, offsets, types, &mpi_type_rank_0_to_3);
        MPI_Type_commit(&mpi_type_rank_0_to_3);
    }
    {
        const int nitems = 3;
        int blocklengths[3] = {1, 1, 1};
        MPI_Datatype types[3] = {MPI_LONG_LONG, MPI_LONG_LONG, MPI_LONG_LONG};
        MPI_Aint offsets[3];
        offsets[0] = offsetof(mpi_rank_0_to_4_t, logic_a);
        offsets[1] = offsetof(mpi_rank_0_to_4_t, logic_b);
        offsets[2] = offsetof(mpi_rank_0_to_4_t, logic_op);
        MPI_Type_create_struct(nitems, blocklengths, offsets, types, &mpi_type_rank_0_to_4);
        MPI_Type_commit(&mpi_type_rank_0_to_4);
    }
    {
        const int nitems = 1;
        int blocklengths[1] = {1};
        MPI_Datatype types[1] = {MPI_LONG_LONG};
        MPI_Aint offsets[1];
        offsets[0] = offsetof(mpi_rank_1_to_0_t, y);
        MPI_Type_create_struct(nitems, blocklengths, offsets, types, &mpi_type_rank_1_to_0);
        MPI_Type_commit(&mpi_type_rank_1_to_0);
    }
    {
        const int nitems = 1;
        int blocklengths[1] = {1};
        MPI_Datatype types[1] = {MPI_LONG_LONG};
        MPI_Aint offsets[1];
        offsets[0] = offsetof(mpi_rank_2_to_0_t, y);
        MPI_Type_create_struct(nitems, blocklengths, offsets, types, &mpi_type_rank_2_to_0);
        MPI_Type_commit(&mpi_type_rank_2_to_0);
    }
    {
        const int nitems = 1;
        int blocklengths[1] = {1};
        MPI_Datatype types[1] = {MPI_LONG_LONG};
        MPI_Aint offsets[1];
        offsets[0] = offsetof(mpi_rank_3_to_0_t, y);
        MPI_Type_create_struct(nitems, blocklengths, offsets, types, &mpi_type_rank_3_to_0);
        MPI_Type_commit(&mpi_type_rank_3_to_0);
    }
    {
        const int nitems = 1;
        int blocklengths[1] = {1};
        MPI_Datatype types[1] = {MPI_LONG_LONG};
        MPI_Aint offsets[1];
        offsets[0] = offsetof(mpi_rank_4_to_0_t, y);
        MPI_Type_create_struct(nitems, blocklengths, offsets, types, &mpi_type_rank_4_to_0);
        MPI_Type_commit(&mpi_type_rank_4_to_0);
    }
}

extern void mpi_send_rank_0_to_1(mpi_rank_0_to_1_t message) {
    MPI_Send(&message, 1, mpi_type_rank_0_to_1, 1, 0, MPI_COMM_WORLD);
}

extern mpi_rank_0_to_1_t mpi_receive_from_rank_0_to_1() {
    mpi_rank_0_to_1_t message;
    MPI_Recv(&message, 1, mpi_type_rank_0_to_1, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    return message;
}

extern void mpi_send_rank_0_to_2(mpi_rank_0_to_2_t message) {
    MPI_Send(&message, 1, mpi_type_rank_0_to_2, 2, 0, MPI_COMM_WORLD);
}

extern mpi_rank_0_to_2_t mpi_receive_from_rank_0_to_2() {
    mpi_rank_0_to_2_t message;
    MPI_Recv(&message, 1, mpi_type_rank_0_to_2, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    return message;
}

extern void mpi_send_rank_0_to_3(mpi_rank_0_to_3_t message) {
    MPI_Send(&message, 1, mpi_type_rank_0_to_3, 3, 0, MPI_COMM_WORLD);
}

extern mpi_rank_0_to_3_t mpi_receive_from_rank_0_to_3() {
    mpi_rank_0_to_3_t message;
    MPI_Recv(&message, 1, mpi_type_rank_0_to_3, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    return message;
}

extern void mpi_send_rank_0_to_4(mpi_rank_0_to_4_t message) {
    MPI_Send(&message, 1, mpi_type_rank_0_to_4, 4, 0, MPI_COMM_WORLD);
}

extern mpi_rank_0_to_4_t mpi_receive_from_rank_0_to_4() {
    mpi_rank_0_to_4_t message;
    MPI_Recv(&message, 1, mpi_type_rank_0_to_4, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    return message;
}

extern void mpi_send_rank_1_to_0(mpi_rank_1_to_0_t message) {
    MPI_Send(&message, 1, mpi_type_rank_1_to_0, 0, 0, MPI_COMM_WORLD);
}

extern mpi_rank_1_to_0_t mpi_receive_from_rank_1_to_0() {
    mpi_rank_1_to_0_t message;
    MPI_Recv(&message, 1, mpi_type_rank_1_to_0, 1, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    return message;
}

extern void mpi_send_rank_2_to_0(mpi_rank_2_to_0_t message) {
    MPI_Send(&message, 1, mpi_type_rank_2_to_0, 0, 0, MPI_COMM_WORLD);
}

extern mpi_rank_2_to_0_t mpi_receive_from_rank_2_to_0() {
    mpi_rank_2_to_0_t message;
    MPI_Recv(&message, 1, mpi_type_rank_2_to_0, 2, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    return message;
}

extern void mpi_send_rank_3_to_0(mpi_rank_3_to_0_t message) {
    MPI_Send(&message, 1, mpi_type_rank_3_to_0, 0, 0, MPI_COMM_WORLD);
}

extern mpi_rank_3_to_0_t mpi_receive_from_rank_3_to_0() {
    mpi_rank_3_to_0_t message;
    MPI_Recv(&message, 1, mpi_type_rank_3_to_0, 3, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    return message;
}

extern void mpi_send_rank_4_to_0(mpi_rank_4_to_0_t message) {
    MPI_Send(&message, 1, mpi_type_rank_4_to_0, 0, 0, MPI_COMM_WORLD);
}

extern mpi_rank_4_to_0_t mpi_receive_from_rank_4_to_0() {
    mpi_rank_4_to_0_t message;
    MPI_Recv(&message, 1, mpi_type_rank_4_to_0, 4, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    return message;
}

int getRank()
{
    int rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    return rank;
}

int getSize()
{
    int size;
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    return size;
}

extern void mpi_initialize() {
    MPI_Init(NULL, NULL);
    initialize_mpi_types();
}

extern void mpi_finalize() {
    cout << "Ending Communication from Rank " << getRank() << endl;
    MPI_Finalize();
}
