// Generated by Metro-MPI

#include <mpi.h>
#include <iostream>
#include <csignal>
#include "Vtile.h"
#include "verilated.h"
#include "metro_mpi.cpp"

uint64_t main_time = 0; // Current simulation time
// This is a 64-bit integer to reduce wrap over issues and
// // allow modulus. You can also use a double, if you wish.
double sc_time_stamp () { // Called by $time in Verilog
    return main_time; // converts to double, to match
    // what SystemC does
}

uint64_t clk = 0;

static Vtile* top = nullptr;
static int rank = -1;
static int size = -1;

const int SHUTDOWN_TAG = 299;

void eval_cycle() {
    top->clk = 0;
    main_time += 250;
    top->eval();
    top->clk = 1;
    main_time += 250;
    top->eval();
}
void cleanup(int signum) {
    if (top) { top->final(); delete top; top = nullptr; }
    mpi_finalize();
    exit(signum);
}

// --- Initialization functions for each partition instance ---
void initialize_partition_u_tile0() {
    std::cout << "Initializing partition u_tile0 for Rank 1..." << std::endl;
    // --- Constant/Init Ports ---
    top->inter_in = 0x0;
    // --- Logic Ports (Zeroed) ---
    // --- Wired Ports (Zeroed) ---
    top->clk = 0;
    top->rst_n = 0;
    top->a = 0;
    top->b = 0;
    top->op = 0;
    top->inter_out = 0;
    top->y = 0;
}

void initialize_partition_u_tile1() {
    std::cout << "Initializing partition u_tile1 for Rank 2..." << std::endl;
    // --- Constant/Init Ports ---
    // --- Logic Ports (Zeroed) ---
    // --- Wired Ports (Zeroed) ---
    top->clk = 0;
    top->rst_n = 0;
    top->a = 0;
    top->b = 0;
    top->op = 0;
    top->inter_in = 0;
    top->inter_out = 0;
    top->y = 0;
}

void initialize_partition_u_tile2() {
    std::cout << "Initializing partition u_tile2 for Rank 3..." << std::endl;
    // --- Constant/Init Ports ---
    // --- Logic Ports (Zeroed) ---
    // --- Wired Ports (Zeroed) ---
    top->clk = 0;
    top->rst_n = 0;
    top->a = 0;
    top->b = 0;
    top->op = 0;
    top->inter_in = 0;
    top->inter_out = 0;
    top->y = 0;
}

void initialize_partition_u_tile3() {
    std::cout << "Initializing partition u_tile3 for Rank 4..." << std::endl;
    // --- Constant/Init Ports ---
    // --- Logic Ports (Zeroed) ---
    // --- Wired Ports (Zeroed) ---
    top->clk = 0;
    top->rst_n = 0;
    top->a = 0;
    top->b = 0;
    top->op = 0;
    top->inter_in = 0;
    top->inter_out = 0;
    top->y = 0;
}

// --- Modular MPI Send/Receive functions for each rank ---

void receive_inputs_for_rank_1() {
    // Receive from Rank 0
    mpi_rank_0_to_1_t req_from_0 = mpi_receive_from_rank_0_to_1();
    top->rst_n = req_from_0.logic_rst_n;
    top->a = req_from_0.logic_a;
    top->b = req_from_0.logic_b;
    top->op = req_from_0.logic_op;
    #ifdef MMPI_PRINTS
        std::cout << "[RECV rank1 <- rank0] rst_n = " << (unsigned int)top->rst_n << std::endl;
        std::cout << "[RECV rank1 <- rank0] a = " << (unsigned int)top->a << std::endl;
        std::cout << "[RECV rank1 <- rank0] b = " << (unsigned int)top->b << std::endl;
        std::cout << "[RECV rank1 <- rank0] op = " << (unsigned int)top->op << std::endl;
    #endif
}

void send_outputs_from_rank_1_to_rank_0() {
    {
        mpi_rank_1_to_0_t resp_to_0{};
        resp_to_0.inter_out = top->inter_out;
        resp_to_0.y = top->y;
        #ifdef MMPI_PRINTS
            std::cout << "[SEND rank1 -> rank0] inter_out = " << (unsigned int)top->inter_out << std::endl;
            std::cout << "[SEND rank1 -> rank0] y = " << (unsigned int)top->y << std::endl;
        #endif
        mpi_send_rank_1_to_0(resp_to_0);
    }
}

void send_outputs_from_rank_1_to_other_ranks() {
    // Send to Rank 2
    {
        mpi_rank_1_to_2_t resp_to_2{};
        resp_to_2.inter_out = top->inter_out;
        #ifdef MMPI_PRINTS
            std::cout << "[SEND rank1 -> rank2] inter_out = " << (unsigned int)top->inter_out << std::endl;
        #endif
        mpi_send_rank_1_to_2(resp_to_2);
    }
}

void receive_inputs_for_rank_2() {
    // Receive from Rank 0
    mpi_rank_0_to_2_t req_from_0 = mpi_receive_from_rank_0_to_2();
    top->rst_n = req_from_0.logic_rst_n;
    top->a = req_from_0.logic_a;
    top->b = req_from_0.logic_b;
    top->op = req_from_0.logic_op;
    top->inter_in = req_from_0.logic_inter_in;
    #ifdef MMPI_PRINTS
        std::cout << "[RECV rank2 <- rank0] rst_n = " << (unsigned int)top->rst_n << std::endl;
        std::cout << "[RECV rank2 <- rank0] a = " << (unsigned int)top->a << std::endl;
        std::cout << "[RECV rank2 <- rank0] b = " << (unsigned int)top->b << std::endl;
        std::cout << "[RECV rank2 <- rank0] op = " << (unsigned int)top->op << std::endl;
        std::cout << "[RECV rank2 <- rank0] inter_in = " << (unsigned int)top->inter_in << std::endl;
    #endif
    // Receive from Rank 1
    mpi_rank_1_to_2_t req_from_1 = mpi_receive_from_rank_1_to_2();
    top->inter_in = req_from_1.inter_out;
    #ifdef MMPI_PRINTS
        std::cout << "[RECV rank2 <- rank1] inter_in = " << (unsigned int)top->inter_in << std::endl;
    #endif
}

void send_outputs_from_rank_2_to_rank_0() {
    {
        mpi_rank_2_to_0_t resp_to_0{};
        resp_to_0.inter_out = top->inter_out;
        resp_to_0.y = top->y;
        #ifdef MMPI_PRINTS
            std::cout << "[SEND rank2 -> rank0] inter_out = " << (unsigned int)top->inter_out << std::endl;
            std::cout << "[SEND rank2 -> rank0] y = " << (unsigned int)top->y << std::endl;
        #endif
        mpi_send_rank_2_to_0(resp_to_0);
    }
}

void send_outputs_from_rank_2_to_other_ranks() {
    // Send to Rank 3
    {
        mpi_rank_2_to_3_t resp_to_3{};
        resp_to_3.inter_out = top->inter_out;
        #ifdef MMPI_PRINTS
            std::cout << "[SEND rank2 -> rank3] inter_out = " << (unsigned int)top->inter_out << std::endl;
        #endif
        mpi_send_rank_2_to_3(resp_to_3);
    }
}

void receive_inputs_for_rank_3() {
    // Receive from Rank 0
    mpi_rank_0_to_3_t req_from_0 = mpi_receive_from_rank_0_to_3();
    top->rst_n = req_from_0.logic_rst_n;
    top->a = req_from_0.logic_a;
    top->b = req_from_0.logic_b;
    top->op = req_from_0.logic_op;
    top->inter_in = req_from_0.logic_inter_in;
    #ifdef MMPI_PRINTS
        std::cout << "[RECV rank3 <- rank0] rst_n = " << (unsigned int)top->rst_n << std::endl;
        std::cout << "[RECV rank3 <- rank0] a = " << (unsigned int)top->a << std::endl;
        std::cout << "[RECV rank3 <- rank0] b = " << (unsigned int)top->b << std::endl;
        std::cout << "[RECV rank3 <- rank0] op = " << (unsigned int)top->op << std::endl;
        std::cout << "[RECV rank3 <- rank0] inter_in = " << (unsigned int)top->inter_in << std::endl;
    #endif
    // Receive from Rank 2
    mpi_rank_2_to_3_t req_from_2 = mpi_receive_from_rank_2_to_3();
    top->inter_in = req_from_2.inter_out;
    #ifdef MMPI_PRINTS
        std::cout << "[RECV rank3 <- rank2] inter_in = " << (unsigned int)top->inter_in << std::endl;
    #endif
}

void send_outputs_from_rank_3_to_rank_0() {
    {
        mpi_rank_3_to_0_t resp_to_0{};
        resp_to_0.inter_out = top->inter_out;
        resp_to_0.y = top->y;
        #ifdef MMPI_PRINTS
            std::cout << "[SEND rank3 -> rank0] inter_out = " << (unsigned int)top->inter_out << std::endl;
            std::cout << "[SEND rank3 -> rank0] y = " << (unsigned int)top->y << std::endl;
        #endif
        mpi_send_rank_3_to_0(resp_to_0);
    }
}

void send_outputs_from_rank_3_to_other_ranks() {
    // Send to Rank 4
    {
        mpi_rank_3_to_4_t resp_to_4{};
        resp_to_4.inter_out = top->inter_out;
        #ifdef MMPI_PRINTS
            std::cout << "[SEND rank3 -> rank4] inter_out = " << (unsigned int)top->inter_out << std::endl;
        #endif
        mpi_send_rank_3_to_4(resp_to_4);
    }
}

void receive_inputs_for_rank_4() {
    // Receive from Rank 0
    mpi_rank_0_to_4_t req_from_0 = mpi_receive_from_rank_0_to_4();
    top->rst_n = req_from_0.logic_rst_n;
    top->a = req_from_0.logic_a;
    top->b = req_from_0.logic_b;
    top->op = req_from_0.logic_op;
    top->inter_in = req_from_0.logic_inter_in;
    #ifdef MMPI_PRINTS
        std::cout << "[RECV rank4 <- rank0] rst_n = " << (unsigned int)top->rst_n << std::endl;
        std::cout << "[RECV rank4 <- rank0] a = " << (unsigned int)top->a << std::endl;
        std::cout << "[RECV rank4 <- rank0] b = " << (unsigned int)top->b << std::endl;
        std::cout << "[RECV rank4 <- rank0] op = " << (unsigned int)top->op << std::endl;
        std::cout << "[RECV rank4 <- rank0] inter_in = " << (unsigned int)top->inter_in << std::endl;
    #endif
    // Receive from Rank 3
    mpi_rank_3_to_4_t req_from_3 = mpi_receive_from_rank_3_to_4();
    top->inter_in = req_from_3.inter_out;
    #ifdef MMPI_PRINTS
        std::cout << "[RECV rank4 <- rank3] inter_in = " << (unsigned int)top->inter_in << std::endl;
    #endif
}

void send_outputs_from_rank_4_to_rank_0() {
    {
        mpi_rank_4_to_0_t resp_to_0{};
        resp_to_0.inter_out = top->inter_out;
        resp_to_0.y = top->y;
        #ifdef MMPI_PRINTS
            std::cout << "[SEND rank4 -> rank0] inter_out = " << (unsigned int)top->inter_out << std::endl;
            std::cout << "[SEND rank4 -> rank0] y = " << (unsigned int)top->y << std::endl;
        #endif
        mpi_send_rank_4_to_0(resp_to_0);
    }
}

void send_outputs_from_rank_4_to_other_ranks() {
    // Rank 4 has no non-zero-rank destinations in this topology.
}

// High-level handler that coordinates the communication cycle
void handle_requests() {
    switch (rank) {
        case 1: {
            receive_inputs_for_rank_1();
            send_outputs_from_rank_1_to_other_ranks();
            eval_cycle();
            send_outputs_from_rank_1_to_rank_0();

            break;
        }
        case 2: {
            receive_inputs_for_rank_2();
            send_outputs_from_rank_2_to_other_ranks();
            eval_cycle();
            send_outputs_from_rank_2_to_rank_0();

            break;
        }
        case 3: {
            receive_inputs_for_rank_3();
            send_outputs_from_rank_3_to_other_ranks();
            eval_cycle();
            send_outputs_from_rank_3_to_rank_0();

            break;
        }
        case 4: {
            receive_inputs_for_rank_4();
            send_outputs_from_rank_4_to_other_ranks();
            eval_cycle();
            send_outputs_from_rank_4_to_rank_0();

            break;
        }
        default: break;
    }
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    mpi_initialize();

    top = new Vtile;

    rank = getRank();
    size = getSize();

    std::cout << "Partition 'tile' is alive on Rank " << rank << " of " << size << std::endl;

    switch (rank) {
        case 1: initialize_partition_u_tile0(); break;
        case 2: initialize_partition_u_tile1(); break;
        case 3: initialize_partition_u_tile2(); break;
        case 4: initialize_partition_u_tile3(); break;
        default: break;
    std::cout << " Reset and init complete!!!" << std::endl;

    }

    top->eval();
    //MPI_Barrier(MPI_COMM_WORLD);

    int itr = 0;
    bool sim_end = false;
    while (!sim_end) {
        if (rank != 0) {
             handle_requests();
        }

        itr++;
        if(itr % 10000 == 0 ) std::cout << " #itr = "<< itr << std::endl;

        int shutdown_flag = 0;
        MPI_Status status;
        MPI_Iprobe(0, SHUTDOWN_TAG, MPI_COMM_WORLD, &shutdown_flag, &status);
        if (shutdown_flag) {
            int dummy;
            MPI_Recv(&dummy, 1, MPI_INT, 0, SHUTDOWN_TAG, MPI_COMM_WORLD, &status);
            sim_end = true;
        }
    }

    //std::cout << "ticks: " << std::setprecision(10) << sc_time_stamp() << " , cycles: " << sc_time_stamp()/500 << std::endl;
    std::cout << "Rank " << rank << ": Shutting down." << std::endl;

    cleanup(0);
    return 0;
}
