// Generated by Metro-MPI for Rank 0 (System) Process
// Include this file in your custom C++ testbench (e.g., sim.cpp)

#ifndef METRO_MPI_RANK0_HARNESS_H
#define METRO_MPI_RANK0_HARNESS_H

#include <mpi.h>
#include "metro_mpi.cpp"
#include <iomanip>
#include <svdpi.h>

extern "C" void dpi_tile(
    svBit partition_id,
    const svBitVecVal* a,
    const svBitVecVal* b,
    const svBitVecVal* op,
    const svBitVecVal* inter_in,
    svBitVecVal* inter_out,
    svBitVecVal* y) {
    switch (partition_id) {
        case 1: {
            mpi_rank_0_to_1_t req;
            unsigned long long a_val = a[0];
            req.logic_a = a_val;
            unsigned long long b_val = b[0];
            req.logic_b = b_val;
            unsigned long long op_val = op[0];
            req.logic_op = op_val;
            mpi_send_rank_0_to_1(req);
            #ifdef MMPI_PRINTS
                std::cout << "[SEND rank0 -> rank1] a = " << (unsigned int)a_val << std::endl;
                std::cout << "[SEND rank0 -> rank1] b = " << (unsigned int)b_val << std::endl;
                std::cout << "[SEND rank0 -> rank1] op = " << (unsigned int)op_val << std::endl;
            #endif
            mpi_rank_1_to_0_t resp = mpi_receive_from_rank_1_to_0();
            inter_out[0] = (svBitVecVal)(resp.inter_out & metro_bit_masks[9]);
            y[0] = (svBitVecVal)(resp.y & metro_bit_masks[9]);
            #ifdef MMPI_PRINTS
                std::cout << "[RECV rank1 -> rank0] inter_out = " << (unsigned int)*inter_out << std::endl;
                std::cout << "[RECV rank1 -> rank0] y = " << (unsigned int)*y << std::endl;
            #endif
            break;
        }
        case 2: {
            mpi_rank_0_to_2_t req;
            unsigned long long a_val = a[0];
            req.logic_a = a_val;
            unsigned long long b_val = b[0];
            req.logic_b = b_val;
            unsigned long long op_val = op[0];
            req.logic_op = op_val;
            unsigned long long inter_in_val = inter_in[0];
            req.logic_inter_in = inter_in_val;
            mpi_send_rank_0_to_2(req);
            #ifdef MMPI_PRINTS
                std::cout << "[SEND rank0 -> rank2] a = " << (unsigned int)a_val << std::endl;
                std::cout << "[SEND rank0 -> rank2] b = " << (unsigned int)b_val << std::endl;
                std::cout << "[SEND rank0 -> rank2] op = " << (unsigned int)op_val << std::endl;
                std::cout << "[SEND rank0 -> rank2] inter_in = " << (unsigned int)inter_in_val << std::endl;
            #endif
            mpi_rank_2_to_0_t resp = mpi_receive_from_rank_2_to_0();
            inter_out[0] = (svBitVecVal)(resp.inter_out & metro_bit_masks[9]);
            y[0] = (svBitVecVal)(resp.y & metro_bit_masks[9]);
            #ifdef MMPI_PRINTS
                std::cout << "[RECV rank2 -> rank0] inter_out = " << (unsigned int)*inter_out << std::endl;
                std::cout << "[RECV rank2 -> rank0] y = " << (unsigned int)*y << std::endl;
            #endif
            break;
        }
        case 3: {
            mpi_rank_0_to_3_t req;
            unsigned long long a_val = a[0];
            req.logic_a = a_val;
            unsigned long long b_val = b[0];
            req.logic_b = b_val;
            unsigned long long op_val = op[0];
            req.logic_op = op_val;
            unsigned long long inter_in_val = inter_in[0];
            req.logic_inter_in = inter_in_val;
            mpi_send_rank_0_to_3(req);
            #ifdef MMPI_PRINTS
                std::cout << "[SEND rank0 -> rank3] a = " << (unsigned int)a_val << std::endl;
                std::cout << "[SEND rank0 -> rank3] b = " << (unsigned int)b_val << std::endl;
                std::cout << "[SEND rank0 -> rank3] op = " << (unsigned int)op_val << std::endl;
                std::cout << "[SEND rank0 -> rank3] inter_in = " << (unsigned int)inter_in_val << std::endl;
            #endif
            mpi_rank_3_to_0_t resp = mpi_receive_from_rank_3_to_0();
            inter_out[0] = (svBitVecVal)(resp.inter_out & metro_bit_masks[9]);
            y[0] = (svBitVecVal)(resp.y & metro_bit_masks[9]);
            #ifdef MMPI_PRINTS
                std::cout << "[RECV rank3 -> rank0] inter_out = " << (unsigned int)*inter_out << std::endl;
                std::cout << "[RECV rank3 -> rank0] y = " << (unsigned int)*y << std::endl;
            #endif
            break;
        }
        case 4: {
            mpi_rank_0_to_4_t req;
            unsigned long long a_val = a[0];
            req.logic_a = a_val;
            unsigned long long b_val = b[0];
            req.logic_b = b_val;
            unsigned long long op_val = op[0];
            req.logic_op = op_val;
            unsigned long long inter_in_val = inter_in[0];
            req.logic_inter_in = inter_in_val;
            mpi_send_rank_0_to_4(req);
            #ifdef MMPI_PRINTS
                std::cout << "[SEND rank0 -> rank4] a = " << (unsigned int)a_val << std::endl;
                std::cout << "[SEND rank0 -> rank4] b = " << (unsigned int)b_val << std::endl;
                std::cout << "[SEND rank0 -> rank4] op = " << (unsigned int)op_val << std::endl;
                std::cout << "[SEND rank0 -> rank4] inter_in = " << (unsigned int)inter_in_val << std::endl;
            #endif
            mpi_rank_4_to_0_t resp = mpi_receive_from_rank_4_to_0();
            inter_out[0] = (svBitVecVal)(resp.inter_out & metro_bit_masks[9]);
            y[0] = (svBitVecVal)(resp.y & metro_bit_masks[9]);
            #ifdef MMPI_PRINTS
                std::cout << "[RECV rank4 -> rank0] inter_out = " << (unsigned int)*inter_out << std::endl;
                std::cout << "[RECV rank4 -> rank0] y = " << (unsigned int)*y << std::endl;
            #endif
            break;
        }
        default: {
            break;
        }
    }
}

void metro_mpi_broadcast_shutdown() {
    std::cout << "[Rank 0] Broadcasting shutdown signal." << std::endl;
    const int SHUTDOWN_TAG = 299;
    for (int rank : {1, 2, 3, 4}) {
        int dummy = 1;
        MPI_Send(&dummy, 1, MPI_INT, rank, SHUTDOWN_TAG, MPI_COMM_WORLD);
    }
}

#endif // METRO_MPI_RANK0_HARNESS_H
